### ISSUE TITLE
[PHP 5] segfault in testSerializerIGBinary

### ISSUE THREAD

**Issue by remicollet** [phpredis/phpredis#1053]
Running test suite against 5.5.38 or 5.6.29
`
testSerializerIGBinary     /var/tmp/rpm-tmp.y18ocY: line 61:  5622 Segmentation fault      (core dumped) /opt/remi/php56/root/usr/bin/php --no-php-ini --define extension=igbinary.so --define extension=/builddir/build/BUILDROOT/php56-php-pecl-redis-3.1.0-1.fc25.remi.x86_64/opt/remi/php56/root/usr/lib64/php/modules/redis.so TestRedis.php
`

**Comment by yatsukhnenko** [comment]
@remicollet, could you show backtrace for this segfault? I realized that I forgot to add testing igbinary by travisci :(

**Comment by remicollet** [comment]
I'm currently working on building this new version (reason for the mass bug filling)

Now that I have detect this (in buildsystem) I will try to reproduce in a standard env, with gdb.

**Comment by remicollet** [comment]
(out of topic), IMHO, with so much changes in this extension, and merging 5/7 code, a RC version will have be a good idea..

**Comment by remicollet** [comment]
```
(gdb) bt
#0  0x00007fffecef1861 in igbinary_unserialize_zval () from /opt/remi/php56/root/usr/lib64/php/modules/igbinary.so
#1  0x00007fffecef4843 in igbinary_unserialize () from /opt/remi/php56/root/usr/lib64/php/modules/igbinary.so
#2  0x00007fffeccaf33d in redis_unserialize () from /dev/shm/BUILDROOT/php56-php-pecl-redis-3.1.0-1.fc25.remi.x86_64/opt/remi/php56/root/usr/lib64/php/modules/redis.so
#3  0x00007fffeccaf697 in redis_mbulk_reply_loop () from /dev/shm/BUILDROOT/php56-php-pecl-redis-3.1.0-1.fc25.remi.x86_64/opt/remi/php56/root/usr/lib64/php/modules/redis.so
#4  0x00007fffeccb04d6 in redis_sock_read_multibulk_reply () from /dev/shm/BUILDROOT/php56-php-pecl-redis-3.1.0-1.fc25.remi.x86_64/opt/remi/php56/root/usr/lib64/php/modules/redis.so
#5  0x00007fffecc8b035 in zim_Redis_lGetRange () from /dev/shm/BUILDROOT/php56-php-pecl-redis-3.1.0-1.fc25.remi.x86_64/opt/remi/php56/root/usr/lib64/php/modules/redis.so
#6  0x000055555578774a in dtrace_execute_internal (execute_data_ptr=<optimized out>, fci=<optimized out>, return_value_used=<optimized out>)
    at /usr/src/debug/php-5.6.29/Zend/zend_dtrace.c:97
#7  0x0000555555847bb7 in zend_do_fcall_common_helper_SPEC (execute_data=<optimized out>) at /usr/src/debug/php-5.6.29/Zend/zend_vm_execute.h:560
#8  0x00005555557d67c0 in execute_ex (execute_data=execute_data@entry=0x7ffff7f7d098) at /usr/src/debug/php-5.6.29/Zend/zend_vm_execute.h:363
#9  0x00005555557876d8 in dtrace_execute_ex (execute_data=0x7ffff7f7d098) at /usr/src/debug/php-5.6.29/Zend/zend_dtrace.c:73
#10 0x0000555555848090 in zend_do_fcall_common_helper_SPEC (execute_data=<optimized out>) at /usr/src/debug/php-5.6.29/Zend/zend_vm_execute.h:592
#11 0x00005555557d67c0 in execute_ex (execute_data=execute_data@entry=0x7ffff7f77840) at /usr/src/debug/php-5.6.29/Zend/zend_vm_execute.h:363
#12 0x00005555557876d8 in dtrace_execute_ex (execute_data=0x7ffff7f77840) at /usr/src/debug/php-5.6.29/Zend/zend_dtrace.c:73
#13 0x0000555555848090 in zend_do_fcall_common_helper_SPEC (execute_data=<optimized out>) at /usr/src/debug/php-5.6.29/Zend/zend_vm_execute.h:592
#14 0x00005555557d67c0 in execute_ex (execute_data=execute_data@entry=0x7ffff7f774c0) at /usr/src/debug/php-5.6.29/Zend/zend_vm_execute.h:363
#15 0x00005555557876d8 in dtrace_execute_ex (execute_data=0x7ffff7f774c0) at /usr/src/debug/php-5.6.29/Zend/zend_dtrace.c:73
#16 0x0000555555848090 in zend_do_fcall_common_helper_SPEC (execute_data=<optimized out>) at /usr/src/debug/php-5.6.29/Zend/zend_vm_execute.h:592
#17 0x00005555557d67c0 in execute_ex (execute_data=execute_data@entry=0x7ffff7f769c0) at /usr/src/debug/php-5.6.29/Zend/zend_vm_execute.h:363
#18 0x00005555557876d8 in dtrace_execute_ex (execute_data=0x7ffff7f769c0) at /usr/src/debug/php-5.6.29/Zend/zend_dtrace.c:73
#19 0x000055555579a721 in zend_execute_scripts (type=type@entry=8, retval=retval@entry=0x0, file_count=file_count@entry=3) at /usr/src/debug/php-5.6.29/Zend/zend.c:1341
#20 0x0000555555734ac0 in php_execute_script (primary_file=0x7fffffffc810) at /usr/src/debug/php-5.6.29/main/main.c:2613
#21 0x0000555555849aef in do_cli (argc=7, argv=0x555555bb6220) at /usr/src/debug/php-5.6.29/sapi/cli/php_cli.c:998
#22 0x000055555560e3c9 in main (argc=7, argv=0x555555bb6220) at /usr/src/debug/php-5.6.29/sapi/cli/php_cli.c:1382

```

**Comment by remicollet** [comment]
Notice: because of this segfault, I prefer to not push this new version in my stable repository with other [PHP Extensions](https://blog.remirepo.net/pages/PECL-extensions-RPM-status), so is in **stable** only for 7.x and in **test** for 5.x

**Comment by yatsukhnenko** [comment]
I'm going to collect issues from users, fix them and release 3.1.1 asap

**Comment by yatsukhnenko** [comment]
@remicollet, could you test fix from PR #1057?

**Comment by remicollet** [comment]
Yes, ASAP

**Comment by yatsukhnenko** [comment]
fixed
