### ISSUE TITLE
PHP 7.0 Segfault

### ISSUE THREAD

**Issue by yatsukhnenko** [phpredis/phpredis#1093]
```
#0  0x0000000801fa735a in thr_kill () from /lib/libc.so.7
#1  0x0000000801fa7346 in raise () from /lib/libc.so.7
#2  0x0000000801fa72c9 in abort () from /lib/libc.so.7
#3  0x000000080200df91 in __assert () from /lib/libc.so.7
#4  0x000000000074dfcb in zend_hash_str_find_bucket (ht=0x802ccaea0, str=0x80d1f31d5 "socket", len=6, h=9223378990879802158) at zend_hash.c:519
#5  0x000000000074def5 in zend_hash_str_find (ht=0x802ccaea0, str=0x80d1f31d5 "socket", len=6) at zend_hash.c:1999
#6  0x000000080d14a5b0 in redis_sock_get_instance (id=0x802c158c0, redis_sock=0x7fffffffc7d8, no_throw=0) at redis.c:447
#7  0x000000080d14a4c3 in redis_sock_get (id=0x802c158c0, redis_sock=0x7fffffffc7d8, no_throw=0) at redis.c:476
#8  0x000000080d14cd01 in zim_Redis_set (execute_data=0x802c158a0, return_value=0x802c157d0) at redis.c:868
#9  0x0000000000714517 in zend_call_function (fci=0x7fffffffc9c8, fci_cache=0x7fffffffc8e0) at zend_execute_API.c:878
#10 0x00000000007137ba in call_user_function_ex (function_table=0x8029f7640, object=0x802ccae50, function_name=0x7fffffffcbc8, retval_ptr=0x802c157d0, param_count=3, 
    params=0x802df0780, no_separation=1, symbol_table=0x0) at zend_execute_API.c:675
#11 0x0000000000713683 in call_user_function (function_table=0x8029f7640, object=0x802ccae50, function_name=0x7fffffffcbc8, retval_ptr=0x802c157d0, param_count=3, 
    params=0x802df0780) at zend_execute_API.c:657
#12 0x000000080d1bdf21 in ra_forward_call (execute_data=0x802c157f0, return_value=0x802c157d0, ra=0x802c02aa0, cmd=0x8111c2228 "set", cmd_len=3, z_args=0x802c15860, 
    z_new_target=0x0) at redis_array.c:397
#13 0x000000080d1b8bf2 in zim_RedisArray___call (execute_data=0x802c157f0, return_value=0x802c157d0) at redis_array.c:439
#14 0x0000000000809249 in ZEND_CALL_TRAMPOLINE_SPEC_HANDLER (execute_data=0x802c15710) at zend_vm_execute.h:1788
#15 0x000000000079ada4 in execute_ex (ex=0x802c15030) at zend_vm_execute.h:417
#16 0x000000000079aee4 in zend_execute (op_array=0x802c69000, return_value=0x0) at zend_vm_execute.h:458
#17 0x0000000000732208 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at zend.c:1437
#18 0x0000000000682311 in php_execute_script (primary_file=0x7fffffffea28) at main.c:2494
#19 0x000000000083e6ec in main (argc=1, argv=0x7fffffffeb30) at /usr/ports/lang/php70/work/php-7.0.14/sapi/fpm/fpm/fpm_main.c:1968
```

**Comment by yatsukhnenko** [comment]
```
#0  0x0000000000591693 in zend_is_callable_ex ()
#1  0x000000000057c55a in zend_call_function ()
#2  0x000000000057c392 in call_user_function ()
#3  0x000000080ce667e8 in ra_forward_call (execute_data=0x802c146d0, return_value=0x802c146b0, ra=0x802c02310, cmd=0x810e26670 "get", cmd_len=3, z_args=0x802c14740, 
    z_new_target=0x1) at redis_array.c:397
#4  0x000000080ce63de2 in zim_RedisArray___call (execute_data=0x802c146d0, return_value=0x802c146b0) at redis_array.c:439
#5  0x0000000000604641 in ZEND_CALL_TRAMPOLINE_SPEC_HANDLER ()
#6  0x00000000005c7ee8 in execute_ex ()
#7  0x00000000005c8104 in zend_execute ()
#8  0x000000000058a5ef in zend_execute_scripts ()
#9  0x000000000052c41a in php_execute_script ()
#10 0x000000000061ef58 in main ()
```

**Comment by michael-grunder** [comment]
Might help find the other redis array segfault we're seeing.

**Comment by yatsukhnenko** [comment]
After merging a765f8d and 8fa85af I don't see this segfaults anymore
