### ISSUE TITLE
Centos 6.5 and gcc 4.4.7 segment fault

### ISSUE THREAD

**Issue by wangjinbei** [phpredis/phpredis#1095]
os: Linux VM_28_230_centos 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

gcc : 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)

php: PHP 7.0.7 (cli) (built: Nov 21 2016 17:49:02) ( NTS )

phpredis  => 3.1.0

When run demo.php display as follow,  segment fault occurs.
But if install in Centos 7 and gcc 4.8.5  , demo operate normal.
 

```
<?php
$i = 100;
while($i--){
             $redis = new \Redis();
             $redis->connect('127.0.0.1', '6381');
             $redis->auth('123456');
             var_dump($redis->hGetAll('11111')); //key 111111 not exist
             usleep(500000);
}
```

```
[Thread debugging using libthread_db enabled]
array(0) {
}
array(0) {
}
Program received signal SIGSEGV, Segmentation fault.
0x00000000008426bc in zend_hash_destroy (ht=0x7ffff0656268) at /usr/local/src/php-7.0.7/Zend/zend_hash.c:1276
1276						ht->pDestructor(&p->val);

BackTrace : 
(gdb) bt
#0  0x00000000008426bc in zend_hash_destroy (ht=0x7ffff0656268) at /usr/local/src/php-7.0.7/Zend/zend_hash.c:1276
#1  0x0000000000846f6d in zend_array_destroy (ht=0x7ffff0656268) at /usr/local/src/php-7.0.7/Zend/zend_hash.c:1325
#2  0x000000000086af16 in zend_object_std_dtor (object=0x7ffff0602640) at /usr/local/src/php-7.0.7/Zend/zend_objects.c:61
#3  0x000000000086f8e5 in zend_objects_store_del (object=0x7ffff0602640) at /usr/local/src/php-7.0.7/Zend/zend_objects_API.c:178
#4  0x0000000000879f4e in zend_assign_to_variable (execute_data=0x7ffff0613030) at /usr/local/src/php-7.0.7/Zend/zend_execute.h:103
#5  ZEND_ASSIGN_SPEC_CV_VAR_HANDLER (execute_data=0x7ffff0613030) at /usr/local/src/php-7.0.7/Zend/zend_vm_execute.h:33556
#6  0x0000000000873950 in execute_ex (ex=<value optimized out>) at /usr/local/src/php-7.0.7/Zend/zend_vm_execute.h:417
#7  0x00000000008c6a0b in zend_execute (op_array=0x7ffff0683000, return_value=<value optimized out>)
    at /usr/local/src/php-7.0.7/Zend/zend_vm_execute.h:458
#8  0x00000000008340e3 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /usr/local/src/php-7.0.7/Zend/zend.c:1427
#9  0x00000000007d68b0 in php_execute_script (primary_file=0x7fffffffe0f0) at /usr/local/src/php-7.0.7/main/main.c:2494
#10 0x00000000008cad6a in do_cli (argc=2, argv=0xebaba0) at /usr/local/src/php-7.0.7/sapi/cli/php_cli.c:974
#11 0x00000000008cb56a in main (argc=2, argv=0xebaba0) at /usr/local/src/php-7.0.7/sapi/cli/php_cli.c:1344
(gdb) print_ft (HashTable *)0x7ffff0656268
A syntax error in expression, near `'.
```

**Comment by yatsukhnenko** [comment]
3.1.4 has been released on PECL site. Open new issue if crash will reproduce
