### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by zhujinhe** [phpredis/phpredis#1110]
I got a lot of warning in php-fpm.log.
`WARNING: [pool www] child 4542 exited on signal 11 (SIGSEGV) after 7.560746 seconds from start`
The coredump is here. Does this mean a memory leak of line 2096. or should i provide other information?
```
gdb /usr/local/php7/sbin/php-fpm /tmp/coredump-php-fpm.15197
......
Core was generated by php-fpm: pool www                                                             '.
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000a25b55 in zend_mm_find_leaks_small (p=0x7fa56b200000, i=510, j=2, leak=0x7fffe747bca0) at /usr/local/src/php-7.0.6/Zend/zend_alloc.c:2004
2004			if (dbg->size != 0) {
Missing separate debuginfos, use: debuginfo-install lcms-libs-1.19-1.el6.x86_64 libICE-1.0.6-1.el6.x86_64 libidn-1.18-2.el6.x86_64 libtidy-0.99.0-19.20070615.1.el6.x86_64 libtool-ltdl-2.2.6-15.5.el6.x86_64 sqlite-3.6.20-1.el6.x86_64
(gdb) bt full
#0  0x0000000000a25b55 in zend_mm_find_leaks_small (p=0x7fa56b200000, i=510, j=2, leak=0x7fffe747bca0) at /usr/local/src/php-7.0.6/Zend/zend_alloc.c:2004
        empty = 1
        count = 0
        bin_num = 29
        dbg = 0x7fa56b4003e0
#1  0x0000000000a25cc2 in zend_mm_find_leaks (heap=0x7fa577e00040, p=0x7fa56b200000, i=510, leak=0x7fffe747bca0)
    at /usr/local/src/php-7.0.6/Zend/zend_alloc.c:2032
        bin_num = 29
        count = 0
#2  0x0000000000a261a9 in zend_mm_check_leaks (heap=0x7fa577e00040) at /usr/local/src/php-7.0.6/Zend/zend_alloc.c:2136
        bin_num = 8
        dbg = 0x7fa56aff99e0
        list = 0x0
        p = 0x7fa56ae00000
        leak = {addr = 0x7fa56aff99b0, size = 36, filename = 0x7fa571b0c600 "/usr/local/src/phpredis-php7/library.c",
          orig_filename = 0x10dda80 "/usr/local/src/php-7.0.6/Zend/zend_alloc.c", lineno = 2096, orig_lineno = 2518}
        repeated = 0
        total = 0
        i = 505
        j = 31
#3  0x0000000000a26469 in zend_mm_shutdown (heap=0x7fa577e00040, full=0, silent=0) at /usr/local/src/php-7.0.6/Zend/zend_alloc.c:2201
        p = 0x48905b
        list = 0x7fffe747bee0
#4  0x0000000000a27251 in shutdown_memory_manager (silent=0, full_shutdown=0) at /usr/local/src/php-7.0.6/Zend/zend_alloc.c:2637
No locals.
#5  0x00000000009cb55f in php_request_shutdown (dummy=0x0) at /usr/local/src/php-7.0.6/main/main.c:1856
        __orig_bailout = 0x7fffe747c0a0
        __bailout = {{__jmpbuf = {0, 6287875955944603597, 4472240, 140737073628288, 0, 0, 6287875959927095245, -6287928427876302899},
            __mask_was_saved = 0, __saved_mask = {__val = {0, 0, 0, 0, 0, 0, 0, 0, 38654705664, 140348657508352, 140348657500224, 140348657508352,
                140348657508416, 140737073627184, 10633958, 140737073627152}}}}
        report_memleaks = 1 '\001'
#6  0x0000000000b27e49 in main (argc=8, argv=0x7fffe747c488) at /usr/local/src/php-7.0.6/sapi/fpm/fpm/fpm_main.c:1996
        primary_script = 0x7fa577e025a0 ""
        __orig_bailout = 0x0
        __bailout = {{__jmpbuf = {0, 6287875956020101069, 4472240, 140737073628288, 0, 0, 6287875955946700749, -6287928648659615795},
            __mask_was_saved = 0, __saved_mask = {__val = {227534740610, 227543104584, 11341735, 257698037805, 227543099064, 0, 140737073627872,
---Type <return> to continue, or q <return> to quit---
                227543104584, 227543123448, 140348680472984, 227534738230, 140348660145344, 140737073627632, 253692616938, 140737073627632, 49}}}}
        exit_status = 0
        cgi = 0
        c = -1
        use_extended_info = 0
        file_handle = {handle = {fd = -163754450, fp = 0xf63d4e2e, stream = {handle = 0xf63d4e2e, isatty = -98525430, mmap = {len = 0,
                pos = 140348660147216, map = 0x7fff00000001, buf = 0x0, old_handle = 0x1, old_closer = 0x34fa421188}, reader = 0x34faa08be0,
              fsizer = 0x7fa57808e000, closer = 0x1dcd010}}, filename = 0x7fa577e02000 "\240%\340w\245\177", opened_path = 0x0,
          type = ZEND_HANDLE_FILENAME, free_filename = 0 '\000'}
        orig_optind = 1
        orig_optarg = 0x0
        ini_entries_len = 0
        max_requests = 600
        requests = 78
        fcgi_fd = 0
        request = 0x1fd0af0
        fpm_config = 0x7fffe747c75a ""
        fpm_prefix = 0x0
        fpm_pid = 0x7fffe747c77d ""
        test_conf = 0
        force_daemon = 1
        force_stderr = 0
        php_information = 0
        php_allow_to_run_as_root = 0
        __func__ = "main"
(gdb) p dbg
$1 = (zend_mm_debug_info *) 0x7fa56b4003e0
(gdb) p bin_num
$2 = 29
(gdb) p dbg->size
Cannot access memory at address 0x7fa56b4003e0
(gdb) p leak->filename
$3 = 0x7fa571b0c600 "/usr/local/src/phpredis-php7/library.c"
(gdb) p leak->lineno
$4 = 2096
```
line 2096:
```
ret = ecalloc(1 + ret_len, 1);
```

**Comment by zhujinhe** [comment]
version: 2.2.8-devphp7

**Comment by remicollet** [comment]
Use master (3.1.1)

**Comment by zhujinhe** [comment]
No more leak detected (3.1.1). Thanks @remicollet .
