### ISSUE TITLE
Can´t load extension with 7.1

### ISSUE THREAD

**Issue by dkrotil** [phpredis/phpredis#1153]
Hello,
trying build redis extension against PHP 7.1, everything looks fine, configure without any error. Make creates redis.so. First strange thing is happening , when I try run "make test" _:

```
Build complete.
Don't forget to run 'make test'.


=====================================================================
PHP         : /opt/php-7.1/bin/php
PHP_SAPI    : cli
PHP_VERSION : 7.1.4
ZEND_VERSION: 3.1.0
PHP_OS      : Linux - Linux pathfinder 4.4.49-92.14-default #1 SMP Fri Mar 24 07:03:38 UTC 2017 (cc5d011) x86_64
INI actual  : /install/phpredis-3.1.2/tmp-php.ini
More .INIs  :
---------------------------------------------------------------------
PHP         : /opt/php-7.1/bin/phpdbg
PHP_SAPI    : phpdbg
PHP_VERSION : 7.1.4
ZEND_VERSION: 3.1.0
PHP_OS      : Linux - Linux pathfinder 4.4.49-92.14-default #1 SMP Fri Mar 24 07:03:38 UTC 2017 (cc5d011) x86_64
INI actual  : /install/phpredis-3.1.2/tmp-php.ini
More .INIs  :
---------------------------------------------------------------------
CWD         : /install/phpredis-3.1.2
Extra dirs  :
VALGRIND    : Not used
=====================================================================
TIME START 2017-04-17 09:36:23
=====================================================================
No tests were run.
```

When I try to load it manually "php -r 'dl("redis.so"); phpinfo();' | grep redis" shows no error, but no loaded redis.

Thanks

**Comment by yatsukhnenko** [comment]
@dkrotil, `make test` doesn't work as expected. You should run tests manually `php tests/TestRedis.php`
Try grep -i redis because in phpinfo it appears as `Redis`

**Comment by dkrotil** [comment]
/opt/php-7.1/bin/php -m don´t show any redis / Redis , trying to run test manually getting this error message >

```
/opt/php-7.1/bin/php tests/TestRedis.php
Note: these tests might take up to a minute. Don't worry :-)
Using PHP version 7.1.4 (64 bits)
Testing class Redis
testMinimumVersion
Fatal error: Uncaught Error: Class 'Redis' not found in /install/phpredis-3.1.2/tests/RedisTest.php:35
Stack trace:
#0 /install/phpredis-3.1.2/tests/RedisTest.php(25): Redis_Test->newInstance()
#1 /install/phpredis-3.1.2/tests/TestSuite.php(147): Redis_Test->setUp()
#2 /install/phpredis-3.1.2/tests/TestRedis.php(43): TestSuite::run('Redis_Test', NULL, '127.0.0.1')
#3 {main}
  thrown in /install/phpredis-3.1.2/tests/RedisTest.php on line 35
```

**Comment by yatsukhnenko** [comment]
Did you run `make install` and register extension in uni file? Also you can load extension via php -d
`php -d extension=modules/redis.so tests/TestRedis.php`

**Comment by dkrotil** [comment]
Hmm, with that command with test start with one error >

Assertion failed (1 !== 0): /install/phpredis-3.1.2/tests/RedisTest.php:171 (testBitsets)

but extension will load, have to look on php.ini

**Comment by dkrotil** [comment]
I had typo in php.ini. Now is working.
