### ISSUE TITLE
coredump happend version=3.1.2

### ISSUE THREAD

**Issue by lilien1010** [phpredis/phpredis#1165]
I have  troubled by the php-redis extension related coredump,

here is my redis extension info,
PHP version is 5.4.40
```
redis

Redis Support => enabled
Redis Version => 3.1.2
Available serializers => php
You have mail in /var/spool/mail/root
```

and here is the php coredump info
```
#0  0x00000000007097cd in _php_stream_write (stream=0x176dd40, 
    buf=buf@entry=0x7f951a482748 "*4\r\n$5\r\nHMGET\r\n$32\r\nMOMENT_REPORTED_HANDLER_INTERVAL\r\n$8\r\nduration\r\n$5\r\ncount\r\n", count=count@entry=79)
    at /usr/local/src/php-5.4.40/main/streams/streams.c:1242
#1  0x00007f951e4c3ed1 in redis_sock_write (redis_sock=redis_sock@entry=0x7f951a480838, 
    cmd=0x7f951a482748 "*4\r\n$5\r\nHMGET\r\n$32\r\nMOMENT_REPORTED_HANDLER_INTERVAL\r\n$8\r\nduration\r\n$5\r\ncount\r\n", sz=79) at /tmp/pear/temp/redis/library.c:1927
#2  0x00007f951e4afb67 in zim_Redis_hMget (ht=2, return_value=0x7f951a463410, return_value_ptr=0x7fffc65db668, this_ptr=0x7f951a481ff0, return_value_used=1)
    at /tmp/pear/temp/redis/redis.c:2184
#3  0x0000000000741243 in zend_call_function (fci=fci@entry=0x7fffc65db6a0, fci_cache=fci_cache@entry=0x7fffc65db670) at /usr/local/src/php-5.4.40/Zend/zend_execute_API.c:978
#4  0x0000000000659d5d in zif_call_user_func_array (ht=<optimized out>, return_value=0x7f951a471488, return_value_ptr=<optimized out>, this_ptr=<optimized out>, 
    return_value_used=<optimized out>) at /usr/local/src/php-5.4.40/ext/standard/basic_functions.c:4754
#5  0x00000000007f2268 in zend_do_fcall_common_helper_SPEC (execute_data=0x7f95248e5e70) at /usr/local/src/php-5.4.40/Zend/zend_vm_execute.h:643
#6  0x0000000000773a8c in execute (op_array=0x7f9524760558) at /usr/local/src/php-5.4.40/Zend/zend_vm_execute.h:410
#7  0x0000000000741181 in zend_call_function (fci=fci@entry=0x7fffc65db990, fci_cache=<optimized out>, fci_cache@entry=0x7fffc65db960)
    at /usr/local/src/php-5.4.40/Zend/zend_execute_API.c:956
#8  0x0000000000763c35 in zend_call_method (object_pp=object_pp@entry=0x7fffc65dba38, obj_ce=<optimized out>, obj_ce@entry=0x7f952475ee78, fn_proxy=fn_proxy@entry=0x7f952475efd0, 
    function_name=function_name@entry=0xcdd957 "__call", function_name_len=function_name_len@entry=6, retval_ptr_ptr=retval_ptr_ptr@entry=0x7fffc65dba58, param_count=param_count@entry=2, 
    arg1=arg1@entry=0x7f951a469340, arg2=0x7f951a4696f8) at /usr/local/src/php-5.4.40/Zend/zend_interfaces.c:97
#9  0x000000000076e5eb in zend_std_call_user_call (ht=<optimized out>, return_value=0x7f951a469c48, return_value_ptr=<optimized out>, this_ptr=0x7f951a46b788, 
    return_value_used=<optimized out>) at /usr/local/src/php-5.4.40/Zend/zend_object_handlers.c:893
#10 0x00000000007f2268 in zend_do_fcall_common_helper_SPEC (execute_data=0x7f95248e5890) at /usr/local/src/php-5.4.40/Zend/zend_vm_execute.h:643
#11 0x0000000000773a8c in execute (op_array=0x1878c90) at /usr/local/src/php-5.4.40/Zend/zend_vm_execute.h:410
#12 0x0000000000741181 in zend_call_function (fci=fci@entry=0x7fffc65dbd50, fci_cache=<optimized out>, fci_cache@entry=0x7fffc65dbd20)
    at /usr/local/src/php-5.4.40/Zend/zend_execute_API.c:956
#13 0x00007f951dde88d7 in zim_amqp_queue_class_consume (ht=<optimized out>, return_value=0x7f951a54eaa8, return_value_ptr=<optimized out>, this_ptr=<optimized out>, 
    return_value_used=<optimized out>) at /usr/local/src/rabbitmq-c-0.5.2/amqp-1.4.0/amqp_queue.c:1005
#14 0x00000000007f2268 in zend_do_fcall_common_helper_SPEC (execute_data=0x7f95248e3bf0) at /usr/local/src/php-5.4.40/Zend/zend_vm_execute.h:643
#15 0x0000000000773a8c in execute (op_array=0x7f952491b088) at /usr/local/src/php-5.4.40/Zend/zend_vm_execute.h:410
#16 0x000000000074f25e in zend_execute_scripts (type=type@entry=8, retval=retval@entry=0x0, file_count=file_count@entry=3) at /usr/local/src/php-5.4.40/Zend/zend.c:1329
#17 0x00000000006f2c49 in php_execute_script (primary_file=primary_file@entry=0x7fffc65de360) at /usr/local/src/php-5.4.40/main/main.c:2502
#18 0x00000000007f40e4 in do_cli (argc=4, argv=0x7fffc65df738) at /usr/local/src/php-5.4.40/sapi/cli/php_cli.c:989
#19 0x0000000000432a38 in main (argc=4, argv=0x7fffc65df738) at /usr/local/src/php-5.4.40/sapi/cli/php_cli.c:1365
```

can anyone explain to me why?

or should I update the PHP

**Comment by yatsukhnenko** [comment]
@lilien1010, do you have a script to reproduce this crash?

**Comment by lilien1010** [comment]
the same problem occur again ,after I update PHP version to 5.5.36.

I want to get config from redis every 10 minutes.
so I create  a  configuration loader function like beblow.
```
	static function getMomentReportedHandleInterval(){
		
		static $_TIME_CNF2	=	[
			'duration'=>86400,
			'count'=>5,
			'lastget'=>0
		];
		
		$now 	=	time();
		if(!empty($_TIME_CNF2) && isset($_TIME_CNF2['lastget']) && $now - $_TIME_CNF2['lastget'] < 10*60 ){
			 
			return $_TIME_CNF2;
			
		}
	 
			  	  
		$redis		=	\RedisCache::getInstance('RULER_REDIS'); 
		  
		$key 		=	'MOMENT_REPORTED_HANDLER_INTERVAL';
		$field 		=	['duration','count'];
		$ret 		=	$redis->hmget($key,$field);
		  
		 if ($ret && isset($ret['duration']) && $ret['count']){
			 
			zLog(HT_INFO,"get duration=".$ret['duration'].",cnt=".$ret['count'],__FUNCTION__,__LINE__);
			  
			 
			$_TIME_CNF2['duration']		=	$ret['duration'];
			$_TIME_CNF2['count']		=	$ret['count'];
			$_TIME_CNF2['lastget']		=	$now;
		 
		 }else{ 
			 zLog(HT_ERROR,"redis data error",__FUNCTION__,__LINE__);	
			  
		 } 
		 
		return $_TIME_CNF2;
	}
```

and for the RedisCache class,  I build it  like this

```php
		
		class RedisCache{
			  
			  protected $pid 	=	'';
			  protected $redis 	=	'';
			  protected $name 	=	'';
			  protected $pcon 	=	false;
			  
			  private $_MAX_TRY_CNT 	=	5;
			  private $_LEFT_RETRY_CNT 	=	5;
			  private $_LAST_FAIL_TIME 	=	0;
			
			  public function __construct($name,$pcon=true,$idx=0)
			  {
					if ( !class_exists('Redis') )
					{
					  throw new Exception('PHP extension does not exist: Redis');
					}
					
					$this->name	=	$name ;
					$this->idx	=	$idx ;
					$this->pcon	=	$pcon ;
					$this->pid	=	posix_getpid();
					
					try{
						$this->redis = getRedisMem($name,$idx,$pcon);
						
					}catch(Exception $e){
						
						zLog(HT_ERROR,$this->pid.','.$this->getMessage()." new redis fail:" ,__CLASS__,__LINE__); 
							 
						throw $e;
					}
			  }
			  
			  public function __call($name, $args){
				  // var_dump($this->redis);
				  if(method_exists($this->redis,$name)){
					  
					redo:
						$reCnt	=	0;
						$runOK	=	true;
						
						try{
							$ret 	=	 call_user_func_array([$this->redis,$name],$args);
							
						}catch(Exception $e){ 
							
							zLog(HT_ERROR,$this->pid.",run $name in {$this->name} redis fail:".$e->getMessage().',left='.$this->_LEFT_RETRY_CNT,__CLASS__,__LINE__); 
							
							$runOK	=	false; 
						}
						
						if($runOK){
							
							if($reCnt>0){
								zLog(HT_CRIT,$this->pid.",{$this->name} run $name OK,left=".$this->_LEFT_RETRY_CNT,__CLASS__,__LINE__); 
							}
							
							$this->_LEFT_RETRY_CNT	=	$this->_MAX_TRY_CNT;
							return $ret;
						}else{
							
							$now 	=	time();
							
							if( $now - $this->_LAST_FAIL_TIME>5){
								$this->reConnect();
								$this->_LAST_FAIL_TIME		=	$now ;
							}
							
							$this->_LEFT_RETRY_CNT--;
							
							if( $this->_LEFT_RETRY_CNT>0){ 
								$reCnt++;
								$this->reConnect();
								goto redo;
							} 
						}
					
				  }else{
					  zLog(HT_ERROR,$this->pid."func={$name} not exist ",__CLASS__,__LINE__); 
							  
					  return false;					  
				  }
					   

			  }
			
			
			public function reConnect(){
				
				zLog(HT_ERROR,$this->pid.", {$this->name} redis reconnect ",__CLASS__,__LINE__); 
							
							
				usleep(500*1000);
				try{  
					
					$this->redis = getRedisMem($this->name,$this->idx,$this->pcon,true);
				 
				}catch(Exception  $e){
					zLog(HT_ERROR,$this->pid.",{$this->name} redis fail:".$e->getMessage() ,__CLASS__,__LINE__); 
				}
			
			}
			
			static function getInstance($name,$pcon=true,$idx=0){
				return new RedisCache($name,$pcon,$idx);
			}
			
		}
```

Is there anything wrong?
@yatsukhnenko

**Comment by yatsukhnenko** [comment]
@lilien1010 your script doesn't crash for me with phpredis 3.1.4RC1. Could you test?

**Comment by yatsukhnenko** [comment]
3.1.4 has been published on PECL site. Please create new issue if crash will reproduce.
