### ISSUE TITLE
Session connection timeout does not work

### ISSUE THREAD

**Issue by nolimitdev** [phpredis/phpredis#1403]
### Expected behaviour
Execution of php script should stop after timeout is reached.

### Actual behaviour
Execution of php script is not ended after defined timeout in session.save_path parameter when redis service is not running.

### I'm seeing this behaviour on
- OS: Linux (Debian)
- Redis: 3.2.11
- PHP: 7.0
- phpredis: 4.1.1

### Steps to reproduce, backtrace or example script
```
<?php
ini_set('session.save_handler', 'redis');
ini_set('session.save_path', 'tcp://localhost:6379?timeout=2&read_timeout=2');
session_start();
echo $_SESSION['count']++; 
?>
```

This script works fine while redis is running. When redis is stopped or unavailable or I use incorrect port or incorrect path to .sock file, script does not end after 2 seconds defined in parameters timeout=2&read_timeout=2. The same problem is when I use unix socket domain instead of TCP `ini_set('session.save_path', 'unix:///tmp/redis.sock?timeout=2&read_timeout=2')`. 

Running this script via apache + nginx as proxy causes nginx error 504 Gateway Time-out after several minutes (depending on proxy timeout). Php max_execution time is default 30 sec. for both master and local value. The problem is that max_execution_time only affects the execution time of the script itself. Any time spent on activity that happens outside the execution of the script (such as redis) is not included when determining the maximum time that the script has been running.

Running this script via PHP CLI seems to be never ending.

### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by nolimitdev** [comment]
There is difference in comparison with Redis:connect() when in mentioned cases (redis is stopped or unavailable or I use incorrect port or incorrect path to .sock file) calling connect() method ends immediately (as expected) with error:

> No such file or directory

... in case unix socket domain

> Connection refused

... in case TCP (host+port)

This behavior of Redis:connect() should be the same for php session ini_set('session.save_handler', 'redis').

**Comment by nolimitdev** [comment]
It is strange. Im getting this issue on two different servers debian 7 + php5 and debian 8 + php7.

**Comment by nolimitdev** [comment]
Im getting this issue also when redis is running and port is correct but server is password protected and I omit auth parameter or use incorrect password = php script is never ending.

**Comment by yatsukhnenko** [comment]
When I changed localhost to github.com

PHP5
```
time php -d extension=modules/redis.so 1403.php 
PHP Fatal error:  Uncaught exception 'RedisException' with message 'Connection closed' in /home/pyatsukhnenko/code/phpredis/1403.php:4
Stack trace:
#0 /home/pyatsukhnenko/code/phpredis/1403.php(4): session_start()
#1 {main}
  thrown in /home/pyatsukhnenko/code/phpredis/1403.php on line 4
PHP Fatal error:  Uncaught exception 'RedisException' with message 'Connection closed' in [no active file]:0
Stack trace:
#0 {main}
  thrown in [no active file] on line 0

real	0m8.188s
user	0m0.019s
sys	0m0.005s
```
PHP7
```
time php -d extension=modules/redis.so 1403.php 
PHP Warning:  session_start(): Failed to read session data: redis (path: tcp://github.com:6379?timeout=2&read_timeout=2) in /home/pyatsukhnenko/code/phpredis/1403.php on line 4
PHP Fatal error:  Uncaught RedisException: Connection closed in /home/pyatsukhnenko/code/phpredis/1403.php:4
Stack trace:
#0 /home/pyatsukhnenko/code/phpredis/1403.php(4): session_start()
#1 {main}
  thrown in /home/pyatsukhnenko/code/phpredis/1403.php on line 4

real	0m6.073s
user	0m0.017s
sys	0m0.006s
```

**Comment by yatsukhnenko** [comment]
> server is password protected and I omit auth parameter or use incorrect password

This is bug. `redis_pool_member_auth` doesn't check server response
@nolimitdev Could you create separated issue for this?

**Comment by nolimitdev** [comment]
What is result of this bug with missing or incorrect auth? Never ending php script?

**Comment by yatsukhnenko** [comment]
I didn't test incorrect auth :)

**Comment by nolimitdev** [comment]
On another server Ubuntu 16.04 I got immediately error in case of incorrect port: Fatal error: Uncaught RedisException: Connection closed in ...
I do not understand why Im getting this never ending script issue on two different Debian servers.

**Comment by yatsukhnenko** [comment]
Is firewall enabled on your Debian server?

**Comment by yatsukhnenko** [comment]
@nolimitdev did you try to run your test script from cli on Debian server?

**Comment by nolimitdev** [comment]
I wrote it in first message

> Running this script via PHP CLI seems to be never ending.

I have to press CTRL+C on Putty terminal to cancel it after long time. It is probably never ending via CLI bacause of max_execution_time is hardcoded to 0 by this comment from php.ini:

> ; Note: This directive is hardcoded to 0 for the CLI SAPI

Can you test it please on some Debian 7 or 8 with phpredis 4.1.1?

**Comment by nolimitdev** [comment]
Something new with this issue? It is very dangerous because it can quickly lead to Denial of Service (DoS) due to run out of available slots to serve clients requests.

**Comment by yatsukhnenko** [comment]
@nolimitdev could you test the latest changes from `develop` branch?

**Comment by nolimitdev** [comment]
@yatsukhnenko I can confirm it is working now! Great job!

Now I get php warning:
- immediately in case of incorrect path to socket file
- after defined timeout in case of incorrect host/port or in case redis is not running
... no more never ending script :)

It was fixed in this commit https://github.com/phpredis/phpredis/commit/4e2de1581f93bfaa790eea91afcbf2fca6324037 ?

**Comment by yatsukhnenko** [comment]
@nolimitdev probably yes :smile: could you close this issue?
