### ISSUE TITLE
PHP crash using unix sock in session.save_path

### ISSUE THREAD

**Issue by VictorVolpe** [phpredis/phpredis#1817]
### Expected behaviour
With "tcp://" works normally...
```
1595567508.534255 [0 127.0.0.1:54673] "EXISTS" "PHPREDIS_SESSION:rv6ubatnunotj9rv89b4t90lhs"
1595567508.534583 [0 127.0.0.1:54673] "GET" "PHPREDIS_SESSION:rv6ubatnunotj9rv89b4t90lhs"
1595567508.535069 [0 127.0.0.1:54673] "SETEX" "PHPREDIS_SESSION:rv6ubatnunotj9rv89b4t90lhs" "1440" ""
```

### Actual behaviour
But with "unix://" crashes at "SETEX" (or maybe at some previous point)
```
1595567582.507999 [0 unix:/var/run/redis/redis.sock] "EXISTS" "PHPREDIS_SESSION:rv6ubatnunotj9rv89b4t90lhs"
1595567582.508225 [0 unix:/var/run/redis/redis.sock] "GET" "PHPREDIS_SESSION:rv6ubatnunotj9rv89b4t90lhs"
...
[24-Jul-2020 02:13:02] WARNING: [pool www] child 58541 exited on signal 10 (SIGBUS) after 0.005763 seconds from start
```

### I'm seeing this behaviour on
- OS: FreeBSD 12.1-RELEASE-p7 GENERIC amd64
- Redis: redis-5.0.9
- PHP: php73-7.3.20
- phpredis: php73-pecl-redis-5.3.0_1

### Steps to reproduce, backtrace or example script
**redis.conf**
```
unixsocket /var/run/redis/redis.sock
unixsocketperm 777
```
**php.ini**
```
session.save_handler=redis
session.save_path="unix:///var/run/redis/redis.sock"
```
**example.php**
```
<?php
session_start();
```
**php-fpm.core**
```
Reading symbols from php-fpm...
[New LWP 100148]
Core was generated by `php-fpm: pool www'.
Program terminated with signal SIGBUS, Bus error.
#0  0x00000000004f6811 in zend_hash_find ()
(gdb) bt
#0  0x00000000004f6811 in zend_hash_find ()
#1  0x00000008016c84e7 in ps_srlzr_encode_php ()
    at /usr/local/lib/php/20180731/session.so
#2  0x00000008016ca315 in php_session_flush ()
    at /usr/local/lib/php/20180731/session.so
#3  0x00000008016ca87b in  () at /usr/local/lib/php/20180731/session.so
#4  0x00000000004ea9f0 in zend_deactivate_modules ()
#5  0x00000000004795f6 in php_request_shutdown ()
#6  0x00000000005ad0df in main ()
(gdb)
```

### I've checked
- [X] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
This was fixed in 066cff6adee03ce05ec5d57083eb7995dfa4344d which is contained in PhpRedis 5.3.1

Somewhat related issue: #1807 

I'm going to close this but if you still have problems with 5.3.1 please let us know.  Just to make sure I tested using a Unix socket in 5.3.0 and 5.3.1 and it's fixed for me.
