### ISSUE TITLE
Couldn't map cluster keyspace using any provided seed Redis-cluster

### ISSUE THREAD

**Issue by Danozavr** [phpredis/phpredis#2450]
### Expected behaviour
Connection to redis-cluster
### Actual behaviour
error "Couldn't map cluster keyspace using any provided seed"
### I'm seeing this behaviour on
- OS: docker image php:8.2-fpm-alpine
- Redis: 7.2.2
- PHP: 8.2
- phpredis: 6.0.2

### Steps to reproduce, backtrace or example script
Connecting Laravel to the Redis cluster
Also when I run [this script](https://gist.github.com/michael-grunder/ec1cd54b321c454d63864091ff288401) from @michael-grunder  [michael-grunder](https://github.com/michael-grunder) it gives the error 
```
Checking general cluster INFO: OK
Warning: Array
(
    [0] => Array
        (
            [0] => 0
            [1] => 5460
            [2] => Array
                (
                    [0] => 10.233.105.146
                    [1] => 6379
                    [2] => 977975c724ed31586967635107a7a8762e733d1e
                    [3] => Array
                        (
                        )

                )

        )

    [1] => Array
        (
            [0] => 5461
            [1] => 10922
            [2] => Array
                (
                    [0] => 10.233.105.147
                    [1] => 6379
                    [2] => ec130564714ce9b8a15be7e791893c89a95c0e3
                    [3] => Array
                        (
                        )

                )

        )

    [2] => Array
        (
            [0] => 10923
            [1] => 16383
            [2] => Array
                (
                    [0] => 10.233.76.46
                    [1] => 6379
                    [2] => c59bf7ed863ddccf7fbe35058f54b29646ba97df
                    [3] => Array
                        (
                        )

                )

        )

)

PHP Fatal error:  Uncaught Error: Call to undefined function panicError() in /app/tests/testclusters.php:12
Stack trace:
#0 /app/tests/testclusters.php(109): panicClusterSlotsError()
#1 /app/tests/testclusters.php(190): checkClusterSlots()
#2 {main}
  thrown in /app/tests/testclusters.php on line 12
```

### I've checked
- [x] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
Can you try running the script again?  Newer versions of Redis added network meta-info about each slot after I wrote it.

**Comment by Danozavr** [comment]
@michael-grunder 
Thank you for your prompt response. Currently the script is working well, here is the output: 
```Checking general cluster INFO: OK
Checking [0:5460] (10.233.102.159:6379): OK
Checking [5461:10922] (10.233.75.1:6379): OK
Checking [10923:16383] (10.233.102.161:6379): OK
Attempting to set key 'phpredis-cluster-key:0'
Redirected to '10.233.102.159:6379'
Success setting 'phpredis-cluster-key:0'
Attempting to set key 'phpredis-cluster-key:1'
Success setting 'phpredis-cluster-key:1'
Attempting to set key 'phpredis-cluster-key:2'
Redirected to '10.233.102.161:6379'
Success setting 'phpredis-cluster-key:2'
Attempting to set key 'phpredis-cluster-key:3'
Redirected to '10.233.75.1:6379'
Success setting 'phpredis-cluster-key:3'
Attempting to set key 'phpredis-cluster-key:4'
Redirected to '10.233.102.159:6379'
Redirected to '10.233.102.161:6379'
Success setting 'phpredis-cluster-key:4'
Attempting to set key 'phpredis-cluster-key:5'
Redirected to '10.233.102.159:6379'
Redirected to '10.233.102.161:6379'
Success setting 'phpredis-cluster-key:5'
Attempting to set key 'phpredis-cluster-key:6'
Redirected to '10.233.102.159:6379'
Success setting 'phpredis-cluster-key:6'
Attempting to set key 'phpredis-cluster-key:7'
Redirected to '10.233.75.1:6379'
Redirected to '10.233.102.159:6379'
Success setting 'phpredis-cluster-key:7'
Attempting to set key 'phpredis-cluster-key:8'
Redirected to '10.233.75.1:6379'
Success setting 'phpredis-cluster-key:8'
Attempting to set key 'phpredis-cluster-key:9'
Redirected to '10.233.102.159:6379'
Redirected to '10.233.75.1:6379'
Success setting 'phpredis-cluster-key:9'
Cluster seems OK
``` 

However, when connecting to Laravel, the problem persists; perhaps the driver also does not take this network meta-info into account

**Comment by michael-grunder** [comment]
It's hard to say for sure what's going on.  All that script does is manually try to communicate across the cluster by doing the same kinds of things that the `RedisCluster` class does.

So if the script can connect then at a basic level of connecting to the various individual nodes everything is fine.  Another thing you could try is manually using `RedisCluster` against this cluster outside of laravel to verify that PhpRedis can connect.

```php
<?php
$default_seeds = ['10.233.102.159:6379', '10.233.75.1:6379', '10.233.102.161:6379'];

$opt = getopt('', ['seeds:', 'user:', 'pass:']);

if (isset($opt['seeds'])) {
    $seeds = explode(',', $opt['seeds']);
} else {
    $seeds = $default_seeds;
}

$user = $opt['user'] ?? NULL;
$pass = $opt['pass'] ?? NULL;

if ($user && ! $pass) {
    fprintf(STDERR, "Can't pass a user without a password\n");
    exit(1);
}

if ($user && $pass) {
    $auth = [$user, $pass];
} else if ($pass) {
    $auth = [$pass];
} else {
    $auth = NULL;
}
var_dump($auth);
$rc = new RedisCluster(NULL, $seeds, NULL, NULL, false, $auth);

for ($i = 0; $i < 10; $i++) {
    try {
        $key = "test_string:$i";
        $val = "test_string:$i:" . uniqid();

        printf("Setting '%s' => '%s': %s\n", $key, $val, $rc->set($key, $val) ? 'OK' : 'ERR');
        printf("Getting '%s': %s\n", $key, $rc->get($key));
    } catch (Exception $ex) {
        fprintf(STDERR, "Error:  {$ex->getMessage()}\n");
        exit(1);
    }
}
```

You can try running that script.  If you have a username and/or password you can pass it.  I picked the seeds from the output above but you can also specify your own seed via command-line args.

The examples below assume you save the above snippet as `rc.php`.

```bash
# Using the default seeds, no username or password
php rc.php 

# Default seeds w/password
php rc.php --pass secret

# Both username and password
php rc.php --user myuser --pass secret

# Different everything
php rc.php --seed 127.0.0.1:7000 --user someuser --pass secret
```

**Comment by michael-grunder** [comment]
Were you able to resolve the issue?

**Comment by michael-grunder** [comment]
Going to close this but happy to provide additional help if you need it
