### ISSUE TITLE
Segfault when trying to write session data

### ISSUE THREAD

**Issue by Toktik** [phpredis/phpredis#308]
We are getting bunch of segfault errors in our /var/log/messages.

We are using ZF, phpredis, apc, igbinary, FreeBSD, PHP-FPM

Here is the gdb output for "bt" and "dump_bt"
```(gdb) dump_bt executor_globals.current_execute_data
[0x801827a58] getSaveHandler() /www/svn/zend-libs/Toktik/Session/Set.php:42 
[0x8018278d0] Toktik_Session_Set::getSaveHandler() /www/svn/zend-libs/Toktik/Session/Set.php:59 
[0x801827630] Toktik_Session_Set->add("6j6omknh8tbr28358gadtp40s7") /www/svn/zend-libs/Toktik/Session/SaveHandler/Phpredis.php:146 
[0x7fffffffc350] Toktik_Session_SaveHandler_Phpredis->write("6j6omknh8tbr28358gadtp40s7", "Zend_Auth|a:1:{s:7:"storage";s:7:"3963623";}") 
(gdb) bt
#0  0x0000000000695cfe in zend_fetch_var_address_helper_SPEC_CONST_VAR (type=0, execute_data=0x801827a58)

```
at zend_vm_execute.h:4836
```
#1  0x00000000006961da in ZEND_FETCH_R_SPEC_CONST_VAR_HANDLER (execute_data=0x801827a58)

```
at zend_vm_execute.h:4863
```
#2  0x0000000000680a01 in execute (op_array=0x80dc8e2c8) at zend_vm_execute.h:410
#3  0x000000000063101d in zend_call_function (fci=0x7fffffffc640, fci_cache=0x7fffffffc320)

```
at /usr/ports/lang/php5/work/php-5.4.10/Zend/zend_execute_API.c:958
```
#4  0x000000000062fe8a in call_user_function_ex (function_table=0x80185e060, object_pp=0x0,

```
function_name=0x80dc99b78, retval_ptr_ptr=0x7fffffffc6e8, param_count=2, params=0x80dadcab0, 
no_separation=1, symbol_table=0x0) at /usr/ports/lang/php5/work/php-5.4.10/Zend/zend_execute_API.c:750
```
#5  0x000000000062fcbd in call_user_function (function_table=0x80185e060, object_pp=0x0,

```
function_name=0x80dc99b78, retval_ptr=0x80dae2670, param_count=2, params=0x7fffffffc7a0)
at /usr/ports/lang/php5/work/php-5.4.10/Zend/zend_execute_API.c:723
```
#6  0x0000000803cc924f in ps_call_handler () from /usr/local/lib/php/20100525-debug/session.so
#7  0x0000000803cc9924 in ps_write_user () from /usr/local/lib/php/20100525-debug/session.so
#8  0x0000000803cbf4a8 in php_session_save_current_state () from /usr/local/lib/php/20100525-debug/session.so
#9  0x0000000803cc3d06 in php_session_flush () from /usr/local/lib/php/20100525-debug/session.so
#10 0x0000000803cc5cd9 in zm_deactivate_session () from /usr/local/lib/php/20100525-debug/session.so
#11 0x000000000064f121 in zend_deactivate_modules () at /usr/ports/lang/php5/work/php-5.4.10/Zend/zend_API.c:2335
#12 0x00000000005b8aea in php_request_shutdown (dummy=0x0)

```
at /usr/ports/lang/php5/work/php-5.4.10/main/main.c:1759
```
#13 0x000000000079ec06 in main (argc=1, argv=0x7fffffffed58)

```
at /usr/ports/lang/php5/work/php-5.4.10/sapi/fpm/fpm/fpm_main.c:1948
```

(gdb) ```

Here is the classes responsible for session management using phpredis (dump_bt points to these)
http://pastebin.com/kaRNXGCa
http://pastebin.com/njmmm2CD

**Comment by michael-grunder** [comment]
I'm closing out old unupdated issues.  If this is still an issue please reopen.
