### ISSUE TITLE
RedisArray reconnection question

### ISSUE THREAD

**Issue by gonzaloserrano** [phpredis/phpredis#552]
Hi,

I'm trying to test the RedisArray reconnection capabilities with the following code: https://gist.github.com/gonzaloserrano/e3cd6a4307b7d9c8e26c

```
$ra = new RedisArray(
    $serversList,
    array(
        "connect_timeout" => 10,
        "retry_timeout" => 3000,
        "retry_interval" => 3000
    )
);
```
Basically to test this i'm using the ```tcpkill``` tool to kill the TCP connections to the first (out of 5) redis servers i'm using in the array.

I'm getting an output similar this:

First iteration:
```
redis2 > set: 0
get: 0
redis1 > set: 1
get: 1
redis4 > set: 2
get: 2
redis4 > set: 3
get: 3
redis2 > set: 4
get: 4
sleep
```
Then before the second iteration is executed i kill the tcp connection to redis1 server.

Second interation:
```
redis2 > set: 0
get: 0
redis1 > set: 1PHP Notice:  Redis::set(): send of 30 bytes failed with errno=32 Broken pipe in /code/redis.php on line 36
PHP Fatal error:  Uncaught exception 'RedisException' with message 'read error on connection' in /code/redis.php:36
Stack trace:
#0 [internal function]: Redis->set('key1', 1)
#1 /code/redis.php(36): RedisArray->__call('set', Array)
#2 /code/redis.php(36): RedisArray->set('key1', 1)
#3 {main}
  thrown in /code/redis.php on line 36
```
The output is thrown very quick so i don't think the 3 seconds retry timeout, 3 seconds retry interval and 10 seconds connection timeout is changing the behaviour. Actually, if i remove the options i get the same result.

Any hints about this?

Thanks!

**Comment by michael-grunder** [comment]
Well if you kill the connection that would put RedisArray into a socket error state which will throw.  I'll take a look at the code and see if the retry interval isn't being honored.

**Comment by gonzaloserrano** [comment]
Hi, did you take a look at this by chance? Thanks!

**Comment by keyganker** [comment]
Anybody explain it?
