### ISSUE TITLE
SIGSEGV with pconnect from CLI with long running script

### ISSUE THREAD

**Issue by razvanphp** [phpredis/phpredis#695]
Here is the trace, I could isolate it and if I switch back to non persistent connections it does not happen anymore.

The script runs for about 1,5 hours, and fails at the end and returns 139. Maybe related to #687?

Debian 8, PHP 5.6.14-0+deb8u1. If you need more info to track this down, please let me know.

Thank you!

```
Core was generated by `php /usr/share/nginx/www/current/application/yiic cache-heater'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000006a16ad in _php_stream_write (stream=0x2ab4f70,
    buf=buf@entry=0x383bc60 "*2\r\n$6\r\nEXISTS\r\n$55\r\nproduction-3.2.0-200[categoryManager:200:categories][1]\r\n",
    count=count@entry=78) at /tmp/buildd/php5-5.6.14+dfsg/main/streams/streams.c:1236

warning: Source file is more recent than executable.
1236        if (buf == NULL || count == 0 || stream->ops->write == NULL) {
(gdb) bt
#0  0x00000000006a16ad in _php_stream_write (stream=0x2ab4f70,
    buf=buf@entry=0x383bc60 "*2\r\n$6\r\nEXISTS\r\n$55\r\nproduction-3.2.0-200[categoryManager:200:categories][1]\r\n",
    count=count@entry=78) at /tmp/buildd/php5-5.6.14+dfsg/main/streams/streams.c:1236
#1  0x00007fb787551823 in redis_sock_write (redis_sock=0x2ad2478,
    cmd=0x383bc60 "*2\r\n$6\r\nEXISTS\r\n$55\r\nproduction-3.2.0-200[categoryManager:200:categories][1]\r\n", sz=78)
    at /home/rgrigore/phpredis-2.2.7/library.c:1808
#2  0x00007fb787537148 in zim_Redis_exists (ht=1, return_value=0x44c9c10, return_value_ptr=0x4e, this_ptr=0x2ad2398,
    return_value_used=1) at /home/rgrigore/phpredis-2.2.7/redis.c:1599
#3  0x00000000006db44a in dtrace_execute_internal (execute_data_ptr=<optimized out>, fci=<optimized out>,
    return_value_used=<optimized out>) at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_dtrace.c:97
#4  0x000000000079b0a0 in zend_do_fcall_common_helper_SPEC (execute_data=0x7fb796399820)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:560
#5  0x0000000000729a50 in execute_ex (execute_data=0x7fb796399820)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:363
#6  0x00000000006db2e8 in dtrace_execute_ex (execute_data=0x7fb796399820)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_dtrace.c:73
#7  0x000000000079b5e3 in zend_do_fcall_common_helper_SPEC (execute_data=0x7fb7963996f8)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:592
#8  0x0000000000729a50 in execute_ex (execute_data=0x7fb7963996f8)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:363
#9  0x00000000006db2e8 in dtrace_execute_ex (execute_data=0x7fb7963996f8)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_dtrace.c:73
#10 0x000000000079b5e3 in zend_do_fcall_common_helper_SPEC (execute_data=0x7fb7963995b0)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:592
#11 0x0000000000729a50 in execute_ex (execute_data=0x7fb7963995b0)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:363
---Type <return> to continue, or q <return> to quit---
#12 0x00000000006db2e8 in dtrace_execute_ex (execute_data=0x7fb7963995b0)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_dtrace.c:73
#13 0x000000000079b5e3 in zend_do_fcall_common_helper_SPEC (execute_data=0x7fb796399478)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:592
#14 0x0000000000729a50 in execute_ex (execute_data=0x7fb796399478)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:363
#15 0x00000000006db2e8 in dtrace_execute_ex (execute_data=0x7fb796399478)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_dtrace.c:73
#16 0x000000000079b5e3 in zend_do_fcall_common_helper_SPEC (execute_data=0x7fb796399198)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:592
#17 0x0000000000729a50 in execute_ex (execute_data=0x7fb796399198)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:363
#18 0x00000000006db2e8 in dtrace_execute_ex (execute_data=0x7fb796399198)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_dtrace.c:73
#19 0x000000000079b5e3 in zend_do_fcall_common_helper_SPEC (execute_data=0x7fb796398ef8)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:592
#20 0x0000000000729a50 in execute_ex (execute_data=0x7fb796398ef8)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:363
#21 0x00000000006db2e8 in dtrace_execute_ex (execute_data=0x7fb796398ef8)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_dtrace.c:73
#22 0x000000000079b5e3 in zend_do_fcall_common_helper_SPEC (execute_data=0x7fb796398d00)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:592
#23 0x0000000000729a50 in execute_ex (execute_data=0x7fb796398d00)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:363
#24 0x00000000006db2e8 in dtrace_execute_ex (execute_data=0x7fb796398d00)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_dtrace.c:73
---Type <return> to continue, or q <return> to quit---
#25 0x000000000079b5e3 in zend_do_fcall_common_helper_SPEC (execute_data=0x7fb7963983e8)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:592
#26 0x0000000000729a50 in execute_ex (execute_data=0x7fb7963983e8)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:363
#27 0x00000000006db2e8 in dtrace_execute_ex (execute_data=0x7fb7963983e8)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_dtrace.c:73
#28 0x000000000079b5e3 in zend_do_fcall_common_helper_SPEC (execute_data=0x7fb7963980e8)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:592
#29 0x0000000000729a50 in execute_ex (execute_data=0x7fb7963980e8)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:363
#30 0x00000000006db2e8 in dtrace_execute_ex (execute_data=0x7fb7963980e8)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_dtrace.c:73
#31 0x00000000006dd17a in zend_call_function (fci=0x7ffdb0d46ec0, fci_cache=0x383bc60)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_execute_API.c:829
#32 0x000000000056f76b in zim_reflection_method_invokeArgs (ht=1, return_value=0x2f31be8, return_value_ptr=0x4e,
    this_ptr=0x2ee6b88, return_value_used=0) at /tmp/buildd/php5-5.6.14+dfsg/ext/reflection/php_reflection.c:3045
#33 0x00000000006db44a in dtrace_execute_internal (execute_data_ptr=<optimized out>, fci=<optimized out>,
    return_value_used=<optimized out>) at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_dtrace.c:97
#34 0x000000000079b0a0 in zend_do_fcall_common_helper_SPEC (execute_data=0x7fb796397e58)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:560
#35 0x0000000000729a50 in execute_ex (execute_data=0x7fb796397e58)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:363
#36 0x00000000006db2e8 in dtrace_execute_ex (execute_data=0x7fb796397e58)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_dtrace.c:73
#37 0x000000000079b5e3 in zend_do_fcall_common_helper_SPEC (execute_data=0x7fb796396f30)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:592
---Type <return> to continue, or q <return> to quit---
#38 0x0000000000729a50 in execute_ex (execute_data=0x7fb796396f30)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:363
#39 0x00000000006db2e8 in dtrace_execute_ex (execute_data=0x7fb796396f30)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_dtrace.c:73
#40 0x000000000079b5e3 in zend_do_fcall_common_helper_SPEC (execute_data=0x7fb796396b68)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:592
#41 0x0000000000729a50 in execute_ex (execute_data=0x7fb796396b68)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:363
#42 0x00000000006db2e8 in dtrace_execute_ex (execute_data=0x7fb796396b68)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_dtrace.c:73
#43 0x000000000079b5e3 in zend_do_fcall_common_helper_SPEC (execute_data=0x7fb796396968)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:592
#44 0x0000000000729a50 in execute_ex (execute_data=0x7fb796396968)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:363
#45 0x00000000006db2e8 in dtrace_execute_ex (execute_data=0x7fb796396968)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_dtrace.c:73
#46 0x000000000079b5e3 in zend_do_fcall_common_helper_SPEC (execute_data=0x7fb7963965f0)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:592
#47 0x0000000000729a50 in execute_ex (execute_data=0x7fb7963965f0)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:363
#48 0x00000000006db2e8 in dtrace_execute_ex (execute_data=0x7fb7963965f0)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_dtrace.c:73
#49 0x000000000079a21c in ZEND_INCLUDE_OR_EVAL_SPEC_TMP_HANDLER (execute_data=0x7fb796396108)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:8392
#50 0x0000000000729a50 in execute_ex (execute_data=0x7fb796396108)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_vm_execute.h:363
---Type <return> to continue, or q <return> to quit---
#51 0x00000000006db2e8 in dtrace_execute_ex (execute_data=0x7fb796396108)
    at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend_dtrace.c:73
#52 0x00000000006edde0 in zend_execute_scripts (type=44781424, type@entry=8, retval=0x383bc60, retval@entry=0x0,
    file_count=78, file_count@entry=3) at /tmp/buildd/php5-5.6.14+dfsg/Zend/zend.c:1341
#53 0x00000000006899e0 in php_execute_script (primary_file=0x7ffdb0d49d20) at /tmp/buildd/php5-5.6.14+dfsg/main/main.c:2597
#54 0x000000000079d050 in do_cli (argc=44781424, argv=0x383bc60) at /tmp/buildd/php5-5.6.14+dfsg/sapi/cli/php_cli.c:994
#55 0x00000000004627ed in main (argc=44781424, argv=0x383bc60) at /tmp/buildd/php5-5.6.14+dfsg/sapi/cli/php_cli.c:1378
(gdb)
```

**Comment by razvanphp** [comment]
This one is also still available, I solved it only by switching back to connect.

**Comment by yatsukhnenko** [comment]
Old issue without any activity for a long time. Feel free to open new issue if crash will reproduce with the latest version of phpredis
