### ISSUE TITLE
Systematic segfault if closing connection then re-connecting

### ISSUE THREAD

**Issue by huguesalary** [phpredis/phpredis#711]
Hi there,

I've been trying to use phpredis with PHP 7 (and the php7 branch), but I always get a segfault running this simple script:

```php
// redis-bug.php
$host = '127.0.0.1';
$port = 6379;

$redis = new \Redis();
$redis->connect($host, $port);
$redis->close();
$redis->connect($host, $port);
$redis->ping();
```

Then: 
`$ php redis-bug.php`
`[1]    68109 bus error (core dumped)`

Here's the backtrace from GDB:
```
#0  0x0000000101261f00 in ?? ()
#1  0x00000001003e17a3 in _php_stream_write_buffer ()
#2  0x00000001003e0f2a in _php_stream_write ()
#3  0x000000010118b432 in redis_sock_write () from /usr/local/opt/php70-redis/redis.so
#4  0x000000010116a4e1 in zim_Redis_ping () from /usr/local/opt/php70-redis/redis.so
#5  0x0000000100419c1e in dtrace_execute_internal ()
#6  0x000000010047b3a9 in ZEND_DO_FCALL_SPEC_HANDLER ()
#7  0x000000010046637a in execute_ex ()
#8  0x0000000100419b57 in dtrace_execute_ex ()
#9  0x00000001004664b8 in zend_execute ()
#10 0x000000010042ab14 in zend_execute_scripts ()
#11 0x00000001003cc1d7 in php_execute_script ()
#12 0x00000001004b8cdf in do_cli ()
#13 0x00000001004b7b08 in main ()
```

and another backtrace with `$redis->select(1);`:
```
#0  0x0000000101261f00 in ?? ()
#1  0x00000001003e17a3 in _php_stream_write_buffer ()
#2  0x00000001003e0f2a in _php_stream_write ()
#3  0x000000010118b432 in redis_sock_write () from /usr/local/opt/php70-redis/redis.so
#4  0x0000000101173fe7 in zim_Redis_select () from /usr/local/opt/php70-redis/redis.so
#5  0x0000000100419c1e in dtrace_execute_internal ()
#6  0x000000010047b3a9 in ZEND_DO_FCALL_SPEC_HANDLER ()
#7  0x000000010046637a in execute_ex ()
#8  0x0000000100419b57 in dtrace_execute_ex ()
#9  0x00000001004664b8 in zend_execute ()
#10 0x000000010042ab14 in zend_execute_scripts ()
#11 0x00000001003cc1d7 in php_execute_script ()
#12 0x00000001004b8cdf in do_cli ()
#13 0x00000001004b7b08 in main ()
```

And here's another backtrace, this time using `$redis->setex('test', 1440, 'test');`
```gdb
#0  0x00000001003e0482 in _php_stream_free ()
#1  0x00000001011855d5 in redis_check_eof () from /usr/local/opt/php70-redis/redis.so
#2  0x000000010118b418 in redis_sock_write () from /usr/local/opt/php70-redis/redis.so
#3  0x0000000101169182 in zim_Redis_setex () from /usr/local/opt/php70-redis/redis.so
#4  0x0000000100419c1e in dtrace_execute_internal ()
#5  0x000000010047b3a9 in ZEND_DO_FCALL_SPEC_HANDLER ()
#6  0x000000010046637a in execute_ex ()
#7  0x0000000100419b57 in dtrace_execute_ex ()
#8  0x00000001004664b8 in zend_execute ()
#9  0x000000010042ab14 in zend_execute_scripts ()
#10 0x00000001003cc1d7 in php_execute_script ()
#11 0x00000001004b8cdf in do_cli ()
#12 0x00000001004b7b08 in main ()
```

I'm running on Mac OS X Yosemite, PHP 7
```
PHP 7.0.1 (cli) (built: Dec 19 2015 20:52:18) ( NTS DEBUG )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
```

**Comment by michael-grunder** [comment]
Thanks for the report.  This happens to me too but it's not immediately apparent why.  I'll look into it and get back to you.

**Comment by michael-grunder** [comment]
Will you please try again.  This no longer crashes for me.

There do appear to be quite a few memory leaks in the php7 branch though so I'll sort those as well.

**Comment by huguesalary** [comment]
It works on my end too!

**Comment by michael-grunder** [comment]
Awesome, please report any other issues you have!
