### ISSUE TITLE
[Segmentation Fault]use subscribe in PHP7

### ISSUE THREAD

**Issue by solupro** [phpredis/phpredis#717]
php version: 7
phpredis branch: php7 (https://github.com/phpredis/phpredis/tree/php7)

php script:
```
<?php
$objRedis = //Redis init;
$objRedis->subscribe(['config_update_event'], function($instance, $channelName, $message) {
    $arrMsg = json_decode($message, true);
    // some code
});
```
gdb info:
```
Core was generated by `/usr/local/php/bin/php /path/to/script'.
Program terminated with signal 11, Segmentation fault.
#0  _array_init (arg=<optimized out>, size=0) at /data/sources/php-7.0.0/Zend/zend_API.c:1060
1060            ZVAL_NEW_ARR(arg);
(gdb) bt
#0  _array_init (arg=<optimized out>, size=0) at /data/sources/php-7.0.0/Zend/zend_API.c:1060
#1  0x00007fe360f84756 in redis_sock_read_multibulk_reply_zval (execute_data=0x7fe361214190, return_value=0x7fe361214180, 
    redis_sock=0x7fe3612683c0, z_tab=0x0) at /data/sources/phpredis-php7/library.c:429
#2  0x00007fe360f8495b in redis_subscribe_response (execute_data=0x7fe361214190, return_value=0x7fe361214180, 
    redis_sock=0x7fe3612683c0, z_tab=0x0, ctx=0x7fe361284b00) at /data/sources/phpredis-php7/library.c:259
#3  0x00007fe360f61fc5 in zim_Redis_subscribe (execute_data=0x7fe361214190, return_value=0x7fe361214180)
    at /data/sources/phpredis-php7/redis.c:2530
#4  0x00000000008913fa in ZEND_DO_FCALL_SPEC_HANDLER (execute_data=0x7fe361214030)
    at /data/sources/php-7.0.0/Zend/zend_vm_execute.h:842
#5  0x000000000084fee0 in execute_ex (ex=<optimized out>) at /data/sources/php-7.0.0/Zend/zend_vm_execute.h:417
#6  0x000000000089f479 in zend_execute (op_array=0x7fe36127f000, return_value=<optimized out>)
    at /data/sources/php-7.0.0/Zend/zend_vm_execute.h:458
#7  0x00000000008130b4 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /data/sources/php-7.0.0/Zend/zend.c:1428
#8  0x00000000007b6d73 in php_execute_script (primary_file=0x7fffe212b500) at /data/sources/php-7.0.0/main/main.c:2471
#9  0x00000000008a0fb1 in do_cli (argc=2, argv=0x2f29ac0) at /data/sources/php-7.0.0/sapi/cli/php_cli.c:974
#10 0x0000000000442698 in main (argc=2, argv=0x2f29ac0) at /data/sources/php-7.0.0/sapi/cli/php_cli.c:1345
```

**Comment by michael-grunder** [comment]
I can replicate this.  It's due to a change in how the reply is processed.  I'll update when I find a solution.

**Comment by michael-grunder** [comment]
Will you please try again?  

Cheers!

**Comment by solupro** [comment]
Had fixed. Thanks :smile:
