### ISSUE TITLE
PHP 7 - Call to undefined method ::isConnected()

### ISSUE THREAD

**Issue by entr** [phpredis/phpredis#743]
In fact the first time it failed with this error it was reported as `mysqlnd::isConnected()` then I pulled from upstream and recompiled phpredis it became what you see below. 

``` log
[28-Jan-2016 14:59:26 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method /\s+/::isConnected() in /var/www/nb/staging/releases/20160128101924/web/app/object-cache.php:733
Stack trace:
#0 /var/www/nb/staging/releases/20160128101924/web/app/object-cache.php(848): WP_Object_Cache->_connect_redis()
#1 /var/www/nb/staging/releases/20160128101924/web/app/object-cache.php(135): WP_Object_Cache->__construct()
#2 /var/www/nb/staging/releases/20160128101924/web/wp/wp-includes/load.php(473): wp_cache_init()
#3 /var/www/nb/staging/releases/20160128101924/web/wp/wp-settings.php(95): wp_start_object_cache()
#4 /var/www/nb/staging/releases/20160128101924/web/wp-config.php(9): require_once('/var/www/nacion...')
#5 /var/www/nb/staging/releases/20160128101924/web/wp/wp-load.php(42): require_once('/var/www/nacion...')
#6 /var/www/nb/staging/releases/20160128101924/web/wp/wp-blog-header.php(12): require_once('/var/www/nacion...')
#7 /var/www/nb/s in /var/www/nb/staging/releases/20160128101924/web/app/object-cache.php on line 733
```

[object-cache.php:733](https://github.com/pantheon-systems/wp-redis/blob/master/object-cache.php#L733)

PHP 7.0.2 compiled from source
Configure Cmd

``` log
'./configure' '--disable-short-tags' '--with-layout=GNU' '--enable-bcmath' '--enable-calendar' '--enable-exif' '--enable-ftp' '--enable-mbstring' '--enable-mbregex' '--enable-pcntl' '--enable-soap' '--enable-sockets' '--enable-wddx' '--enable-zip' '--enable-opcache' '--enable-mysqlnd' '--enable-intl' '--with-mcrypt' '--with-openssl' '--with-openssl-dir=/usr/bin' '--with-curl' '--with-zlib' '--with-gettext' '--with-mysqli' '--with-pdo-mysql' '--with-mysql-sock=/var/run/mysqld/mysqld.sock' '--with-gd' '--enable-gd-native-ttf' '--with-libdir=/usr/lib/x86_64-linux-gnu' '--with-jpeg-dir=/usr/lib/x86_64-linux-gnu' '--prefix=/opt/phpfarm/inst/php-7.0.2' '--exec-prefix=/opt/phpfarm/inst/php-7.0.2' '--without-pear' '--enable-cgi' '--enable-cli' '--enable-fpm'
```

phpredis 7b3695768213910c9ce5535edd15785118848ca7

Am I missing something?

**Comment by michael-grunder** [comment]
I'm not sure.  I just tested it with a simple script, but I can call `isConnected` just fine.  

What's specifically on this line: `object-cache.php:733`

**Comment by entr** [comment]
It was supposed to be a ref to the actual error line but master apparently changed. Now this should be right [object-cache.php:733](https://github.com/pantheon-systems/wp-redis/blob/v0.2.2/object-cache.php#L733)

**Comment by michael-grunder** [comment]
Oh sorry about that, I totally missed the fact that you referenced the file.

Honestly this is a weird one.  It doesn't appear that this code has changed for a long time:

```
➜  redis git:(php7) ✗ git blame redis.c|grep isConnected
ef792320 (michael-grunder     2013-03-27 10:21:18 -0700  305)      PHP_ME(Redis, isConnected, NULL, ZEND_ACC_PUBLIC)
ef792320 (michael-grunder     2013-03-27 10:21:18 -0700 3529) PHP_METHOD(Redis, isConnected) {
➜  redis git:(php7) ✗ git blame php_redis.h|grep isConnected
ef792320 (michael-grunder     2013-03-27 10:21:18 -0700 221) PHP_METHOD(Redis, isConnected);
```

Also I don't have a problem calling this method in a little test script, and nothing is jumping out at me.  If you're seeing other methods that don't exist then it could be a problem with the build somehow.

I suppose you could try just using the result from the `connect` call itself for a quick workaround but it would be good to figure out why this is happening.

**Comment by yatsukhnenko** [comment]
Old issue without any activity for a long time
