### ISSUE TITLE
SIGILL in redis_set_watch() on `pear upgrade-all` in Ubuntu 14.04 / Debian jessie

### ISSUE THREAD

**Issue by nacc** [phpredis/phpredis#785]
Hello,

Please feel free to close/reject this issue, but I was hoping for some help debugging a weird issue seen by an Ubuntu (php 5.5.9+dfsg-1ubuntu4.14) user, which I've also reproduced with Debian (php 5.6.19+dfsg-0+deb8u1).

Given a fresh 14.04 install (I used an lxd container):

```
# apt-get install php5-dev php-pear php5-redis
...
# pear update-channels
...
# pear upgrade-all
...
Build process completed successfully
Installing '/usr/lib/php5/20121212/redis.so'
upgrade-all ok: channel://pecl.php.net/redis-2.2.7
configuration option "php_ini" is not set to php.ini location
You should add "extension=redis.so" to php.ini

Program received signal SIGILL, Illegal instruction.
```

I did an `export CFLAGS='-g -O0'` and got via gdb:

```
(gdb) bt
#0  0x00007fffefe45b30 in redis_set_watch ()
   from /usr/lib/php5/20121212/redis.so
#1  0x00000000006f5534 in zend_deactivate_modules ()
    at /build/php5-pO28mL/php5-5.5.9+dfsg/Zend/zend_API.c:2433
#2  0x000000000068e665 in php_request_shutdown (dummy=dummy@entry=0x0)
    at /build/php5-pO28mL/php5-5.5.9+dfsg/main/main.c:1777
#3  0x000000000079f25a in do_cli (argc=23, argv=0xebe8f0)
    at /build/php5-pO28mL/php5-5.5.9+dfsg/sapi/cli/php_cli.c:1177
#4  0x0000000000461d90 in main (argc=23, argv=0xebe8f0)
    at /build/php5-pO28mL/php5-5.5.9+dfsg/sapi/cli/php_cli.c:1378
(gdb) disassemble $pc-32,$pc+32
Dump of assembler code from 0x7fffefe45b10 to 0x7fffefe45b50:
   0x00007fffefe45b10 <zm_activate_redis+0>:    add    %al,0x26(%rbx)
   0x00007fffefe45b16:  add    %al,(%rax)
   0x00007fffefe45b18:  (bad)  
   0x00007fffefe45b19:  add    %al,(%rax)
   0x00007fffefe45b1b:  add    %bh,(%rbx)
   0x00007fffefe45b1d:  add    %al,(%rax)
   0x00007fffefe45b1f:  add    %al,(%rax)
   0x00007fffefe45b21 <zm_deactivate_redis+1>:  add    %al,(%rax)
   0x00007fffefe45b23:  add    %al,(%rax)
   0x00007fffefe45b25:  add    %al,(%rax)
   0x00007fffefe45b27:  add    %cl,(%rax)
   0x00007fffefe45b29:  andl   $0x0,(%rsi)
   0x00007fffefe45b2c:  add    %al,(%rax)
   0x00007fffefe45b2e:  add    %al,(%rax)
=> 0x00007fffefe45b30 <redis_set_watch+0>:  (bad)  
   0x00007fffefe45b31 <redis_set_watch+1>:  add    %al,(%rax)
   0x00007fffefe45b33 <redis_set_watch+3>:  add    %ch,0x1(%rip)        # 0x7fffefe45b3a
   0x00007fffefe45b39:  add    %al,(%rax)
   0x00007fffefe45b3b:  add    %al,(%rax)
   0x00007fffefe45b3d:  add    %al,(%rax)
   0x00007fffefe45b3f:  add    %dl,(%rax)
   0x00007fffefe45b41 <redis_clear_watch+1>:    andl   $0x0,(%rsi)
   0x00007fffefe45b44 <redis_clear_watch+4>:    add    %al,(%rax)
   0x00007fffefe45b46 <redis_clear_watch+6>:    add    %al,(%rax)
   0x00007fffefe45b48:  (bad)  
   0x00007fffefe45b49:  add    %al,(%rax)
   0x00007fffefe45b4b:  add    %bh,(%rax,%rax,1)
   0x00007fffefe45b4e:  add    %al,(%rax)
```

I know very little about php-redis, but is the issue looks a bit like zm_deactivate_redis is possibly incorrectly terminated? Not sure, tbh, but am happy to debug any suggestions.

**Comment by yatsukhnenko** [comment]
Probably fixed
