### ISSUE TITLE
Weird exceptions on read timeout

### ISSUE THREAD

**Issue by ProgerXP** [phpredis/phpredis#833]
```
$redis = new Redis;
$redis->connect('127.0.0.1');
$redis->setOption(Redis::OPT_READ_TIMEOUT, 1);
$redis->rawCommand('debug', 'sleep', 5);
```

This generates two exceptions:

```
PHP Fatal error:  Uncaught exception 'RedisException' with message 'socket error on read socket' in b.php:5
Stack trace:
#0 b.php(5): Redis->rawcommand('debug', 'sleep', 5)
#1 {main}

Next exception 'RedisException' with message 'protocol error, got '�' as reply-type byte
' in b.php:5
Stack trace:
#0 b.php(0): Redis->rawcommand()
#1 {main}
  thrown in b.php on line 5
```

What's that corrupted byte in the 2nd exception?

Shouldn't the 1st message be more clear about the cause (read timeout, not some network error)?

**Comment by yatsukhnenko** [comment]
Probably fixed

**Comment by valerianpereira** [comment]
what was the fix? Could you share the solution, please?
