### ISSUE TITLE
phpredis set with EX,NX cause coredump

### ISSUE THREAD

**Issue by zhuleilei** [phpredis/phpredis#971]
env:
- php-7.0.7 
- phpredis 3.0.0

i got two type of coredump in online server
first one: [download](https://www.dropbox.com/s/0pqbi6ii3hnsw7a/coredump1.7z?dl=0)

```
#0  redis_set_cmd (execute_data=<value optimized out>, return_value=<value optimized out>, redis_sock=<value optimized out>, cmd=0x7fffe4d76298, cmd_len=0x7fffe4d762ac, slot=0x0, ctx=0x7fffe4d76290) at /root/phpredis-3.0.0/redis_commands.c:1256
1256                } else if (Z_TYPE_P(v) == IS_STRING && IS_NX_XX_ARG(Z_STRVAL_P(v))) {
(gdb) bt
#0  redis_set_cmd (execute_data=<value optimized out>, return_value=<value optimized out>, redis_sock=<value optimized out>, cmd=0x7fffe4d76298, cmd_len=0x7fffe4d762ac, slot=0x0, ctx=0x7fffe4d76290) at /root/phpredis-3.0.0/redis_commands.c:1256
#1  0x00007f0e9d56573b in zim_Redis_set (execute_data=0x7f0ea4815e40, return_value=0x7fffe4d76480) at /root/phpredis-3.0.0/redis.c:826
#2  0x00000000007fa6e8 in zend_call_function (fci=0x7fffe4d76400, fci_cache=0x7fffe4d76450) at /root/source/php-7.0.7/Zend/zend_execute_API.c:885
#3  0x0000000000674811 in zim_reflection_method_invokeArgs (execute_data=<value optimized out>, return_value=0x7f0ea4815d30) at /root/source/php-7.0.7/ext/reflection/php_reflection.c:3348
#4  0x000000000087eef8 in ZEND_DO_FCALL_SPEC_HANDLER (execute_data=0x7f0ea4815c40) at /root/source/php-7.0.7/Zend/zend_vm_execute.h:842
#5  0x0000000000846e70 in execute_ex (ex=<value optimized out>) at /root/source/php-7.0.7/Zend/zend_vm_execute.h:417
#6  0x00000000007fa678 in zend_call_function (fci=0x7fffe4d76680, fci_cache=0x7fffe4d766d0) at /root/source/php-7.0.7/Zend/zend_execute_API.c:866
#7  0x0000000000672dd9 in zim_reflection_method_invoke (execute_data=<value optimized out>, return_value=0x7f0ea48153f0) at /root/source/php-7.0.7/ext/reflection/php_reflection.c:3234
#8  0x000000000087eef8 in ZEND_DO_FCALL_SPEC_HANDLER (execute_data=0x7f0ea48152c0) at /root/source/php-7.0.7/Zend/zend_vm_execute.h:842
#9  0x0000000000846e70 in execute_ex (ex=<value optimized out>) at /root/source/php-7.0.7/Zend/zend_vm_execute.h:417
#10 0x0000000000899f2b in zend_execute (op_array=0x7f0ea4873000, return_value=<value optimized out>) at /root/source/php-7.0.7/Zend/zend_vm_execute.h:458
#11 0x0000000000807603 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /root/source/php-7.0.7/Zend/zend.c:1427
#12 0x00000000007a9de0 in php_execute_script (primary_file=0x7fffe4d78e60) at /root/source/php-7.0.7/main/main.c:2494
#13 0x00000000008a7dbe in main (argc=<value optimized out>, argv=<value optimized out>) at /root/source/php-7.0.7/sapi/fpm/fpm/fpm_main.c:1968
```

the second one:[download](https://www.dropbox.com/s/hmhqjw9gdljhhpj/coredump2.7z?dl=0)

```
#0  zval_get_type (execute_data=<value optimized out>, return_value=<value optimized out>, redis_sock=<value optimized out>, cmd=0x7fffe4d76298, cmd_len=0x7fffe4d762ac, slot=0x0, ctx=0x7fffe4d76290) at /usr/local/webserver/php-7.0.7/include/php/Zend/zend_types.h:327
327     return pz->u1.v.type;
(gdb) bt
#0  zval_get_type (execute_data=<value optimized out>, return_value=<value optimized out>, redis_sock=<value optimized out>, cmd=0x7fffe4d76298, cmd_len=0x7fffe4d762ac, slot=0x0, ctx=0x7fffe4d76290) at /usr/local/webserver/php-7.0.7/include/php/Zend/zend_types.h:327
#1  redis_set_cmd (execute_data=<value optimized out>, return_value=<value optimized out>, redis_sock=<value optimized out>, cmd=0x7fffe4d76298, cmd_len=0x7fffe4d762ac, slot=0x0, ctx=0x7fffe4d76290) at /root/phpredis-3.0.0/redis_commands.c:1248
#2  0x00007f0e9d56573b in zim_Redis_set (execute_data=0x7f0ea4815e40, return_value=0x7fffe4d76480) at /root/phpredis-3.0.0/redis.c:826
#3  0x00000000007fa6e8 in zend_call_function (fci=0x7fffe4d76400, fci_cache=0x7fffe4d76450) at /root/source/php-7.0.7/Zend/zend_execute_API.c:885
#4  0x0000000000674811 in zim_reflection_method_invokeArgs (execute_data=<value optimized out>, return_value=0x7f0ea4815d30) at /root/source/php-7.0.7/ext/reflection/php_reflection.c:3348
#5  0x000000000087eef8 in ZEND_DO_FCALL_SPEC_HANDLER (execute_data=0x7f0ea4815c40) at /root/source/php-7.0.7/Zend/zend_vm_execute.h:842
#6  0x0000000000846e70 in execute_ex (ex=<value optimized out>) at /root/source/php-7.0.7/Zend/zend_vm_execute.h:417
#7  0x00000000007fa678 in zend_call_function (fci=0x7fffe4d76680, fci_cache=0x7fffe4d766d0) at /root/source/php-7.0.7/Zend/zend_execute_API.c:866
#8  0x0000000000672dd9 in zim_reflection_method_invoke (execute_data=<value optimized out>, return_value=0x7f0ea48153f0) at /root/source/php-7.0.7/ext/reflection/php_reflection.c:3234
#9  0x000000000087eef8 in ZEND_DO_FCALL_SPEC_HANDLER (execute_data=0x7f0ea48152c0) at /root/source/php-7.0.7/Zend/zend_vm_execute.h:842
#10 0x0000000000846e70 in execute_ex (ex=<value optimized out>) at /root/source/php-7.0.7/Zend/zend_vm_execute.h:417
#11 0x0000000000899f2b in zend_execute (op_array=0x7f0ea4876000, return_value=<value optimized out>) at /root/source/php-7.0.7/Zend/zend_vm_execute.h:458
#12 0x0000000000807603 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /root/source/php-7.0.7/Zend/zend.c:1427
#13 0x00000000007a9de0 in php_execute_script (primary_file=0x7fffe4d78e60) at /root/source/php-7.0.7/main/main.c:2494
#14 0x00000000008a7dbe in main (argc=<value optimized out>, argv=<value optimized out>) at /root/source/php-7.0.7/sapi/fpm/fpm/fpm_main.c:1968
```

After include the php's gdbinit , it happens in the same code like

```
(gdb) zbacktrace 
[0x7f0ea4815e40] Redis->set("mjuanpi_goods_logic_goodsdefaultexpress_f729f6419465e811f4787f27c8d22da3.lock", 1, array(2)[0x7f0ea4815ec0]) [internal function]
[0x7f0ea4815dc0] ReflectionMethod->invokeArgs(object[0x7f0ea4815e20], array(3)[0x7f0ea4815e30]) [internal function]
[0x7f0ea4815c40] TraceRedis->__call("set", array(3)[0x7f0ea4815cb0]) /data/htdocs/backup/JUANPI_V3/juanpi_v3/JUANPI_V3.zhunbeibak/Common/TraceRedis.php:92 
[0x7f0ea4815b20] TraceRedis->cache("goods_logic_goodsdefaultexpress_f729f6419465e811f4787f27c8d22da3", array(2)[0x7f0ea4815b90], 0, "mjuanpi_") /data/htdocs/backup/JUANPI_V3/juanpi_v3/JUANPI_V3.zhunbeibak/Common/TraceRedis.php:185 
[0x7f0ea48159b0] CacheModel->__call("goodsDefaultExpress", array(1)[0x7f0ea4815a20]) /data/htdocs/backup/JUANPI_V3/juanpi_v3/JUANPI_V3.zhunbeibak/Model/CacheModel.class.php:56 
[0x7f0ea48158d0] GoodsLogic->_tm_goods_info(2969083) /data/htdocs/backup/JUANPI_V3/juanpi_v3/JUANPI_V3.zhunbeibak/Logic/GoodsLogic.class.php:2481 
[0x7f0ea4815760] CacheModel->__call("tm_goods_info", array(1)[0x7f0ea48157d0]) /data/htdocs/backup/JUANPI_V3/juanpi_v3/JUANPI_V3.zhunbeibak/Model/CacheModel.class.php:60 
[0x7f0ea4815490] MallAction->h5_detail() /data/htdocs/backup/JUANPI_V3/juanpi_v3/JUANPI_V3.zhunbeibak/Apps/Mjuanpi/Action/MallAction.class.php:183 
[0x7f0ea4815420] ReflectionMethod->invoke(object[0x7f0ea4815480]) [internal function]
[0x7f0ea48152c0] App::exec() /data/htdocs/working/JUANPI_V3/Runtime/~runtime.php:1 
[0x7f0ea4815250] App::run() /data/htdocs/working/JUANPI_V3/Runtime/~runtime.php:1 
[0x7f0ea48151e0] Think::start() /data/htdocs/working/JUANPI_V3/Runtime/~runtime.php:1 
[0x7f0ea4815150] (main) /data/htdocs/working/JUANPI_V3/Runtime/~runtime.php:1 
[0x7f0ea48150b0] (main) /data/htdocs/backup/JUANPI_V3/juanpi_v3/JUANPI_V3.zhunbeibak/vendor/juanpi/tpv3/ThinkPHP.php:31 
[0x7f0ea4815030] (main) /data/htdocs/INDEX/index.php:31 
```

in php code like this:

``` php
<?php
$redis->set("mjuanpi_goods_logic_goodsdefaultexpress_f729f6419465e811f4787f27c8d22da3.lock",1,['EX'=>120,'NX']);
```

but it's not cause coredump always.so i never repeate it in my own server.But it still happens online sometimes.

**Comment by mikehb** [comment]
I got the same issue

**Comment by yatsukhnenko** [comment]
@mikehb what environment and what version of phpredis do you use?

**Comment by mikehb** [comment]
CentOS 6.7
PHP 7.0.12
PHP Redis 3.0.0

**Comment by yatsukhnenko** [comment]
phpredis 3.0.0 from pecl or php7 branch? Did you try code from develop branch? Issue should be fixed :)

**Comment by mikehb** [comment]
I downloaded the code from this github tag 3.0.0. Should I download the latest code to get the fix

**Comment by yatsukhnenko** [comment]
Yep, try code from develop branch

**Comment by mikehb** [comment]
Is it stable to use

**Comment by yatsukhnenko** [comment]
Nobody knows :smile:

**Comment by mikehb** [comment]
thanks，I would take some time to test

**Comment by zhuleilei** [comment]
@mikehb  ,the newest develop branch has fixed the problem???

**Comment by yatsukhnenko** [comment]
@zhuleilei, yep, this error should be fixed. I hope :)

**Comment by mikehb** [comment]
@zhuleilei @yatsukhnenko should have been fixed after running on my 3 computers for a whole week.

**Comment by zhuleilei** [comment]
thanks all, but after upgrade from 3.0 to the newest develop branch version  3.1.0-rc1, php become more unstable
see #1036

**Comment by zhuleilei** [comment]
I got the following backtraces

```bash
Program terminated with signal 11, Segmentation fault.
#0  0x00007fe9b2299c20 in zim_Redis_bitpos (execute_data=0x7fe9b8e15f10, return_value=0x13351b0) at /root/phpredis/redis.c:795
795	    REDIS_PROCESS_CMD(bitpos, redis_long_response);
Missing separate debuginfos, use: debuginfo-install php-7.0.7-1.el6.x86_64
(gdb) bt
#0  0x00007fe9b2299c20 in zim_Redis_bitpos (execute_data=0x7fe9b8e15f10, return_value=0x13351b0) at /root/phpredis/redis.c:795
#1  0x00007fe9b8e15030 in ?? ()
#2  0x00007fe9b8e7a000 in ?? ()
#3  0x0000000000000000 in ?? ()
(gdb) zbt
Undefined command: "zbt".  Try "help".
(gdb) zbacktrace 
[0x7fe9b8e15f10] Redis->__construct() [internal function]


Program terminated with signal 11, Segmentation fault.
#0  0x0000000000000000 in ?? ()
Missing separate debuginfos, use: debuginfo-install php-7.0.7-1.el6.x86_64
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x000000000080dd80 in zend_activate_modules () at /root/source/php-7.0.7/Zend/zend_API.c:2543
#2  0x00000000007aafa1 in php_request_startup () at /root/source/php-7.0.7/main/main.c:1629
#3  0x00000000008a7d52 in main (argc=<value optimized out>, argv=<value optimized out>) at /root/source/php-7.0.7/sapi/fpm/fpm/fpm_main.c:1906

Program terminated with signal 7, Bus error.
#0  0x00007fe9b2280490 in redis_build_pubsub_cmd (redis_sock=0x1, ret=0x4e, type=<value optimized out>, arg=0x0) at /root/phpredis/redis.c:2933
2933	        redis_cmd_init_sstr(&cmd, zend_hash_num_elements(ht_chan)+1, "PUBSUB",
Missing separate debuginfos, use: debuginfo-install php-7.0.7-1.el6.x86_64
(gdb) bt
#0  0x00007fe9b2280490 in redis_build_pubsub_cmd (redis_sock=0x1, ret=0x4e, type=<value optimized out>, arg=0x0) at /root/phpredis/redis.c:2933
#1  0x0000000000000000 in ?? ()
(gdb) zbacktrace 
(gdb) 


Program terminated with signal 11, Segmentation fault.
#0  zend_mm_free_heap (ptr=0x54ffffffff) at /root/source/php-7.0.7/Zend/zend_alloc.c:1408
1408	/root/source/php-7.0.7/Zend/zend_alloc.c: No such file or directory.
	in /root/source/php-7.0.7/Zend/zend_alloc.c
Missing separate debuginfos, use: debuginfo-install php-7.0.7-1.el6.x86_64
(gdb) bt
#0  zend_mm_free_heap (ptr=0x54ffffffff) at /root/source/php-7.0.7/Zend/zend_alloc.c:1408
#1  _efree (ptr=0x54ffffffff) at /root/source/php-7.0.7/Zend/zend_alloc.c:2466
#2  0x00007fe9b22c1627 in cluster_unsub_resp (execute_data=0x7fe9b8fbb488, return_value=0x7fe9b8fbb488, c=0x7fe9b8f96050, ctx=<value optimized out>) at /root/phpredis/cluster_library.c:1725
#3  0x0000000000000000 in ?? ()
(gdb) zbacktrace 
[0x7fe9b8e159b0] RedisCluster->mget(array(1)[0x7fe9b8e15a10]) [internal function]

```
and the backtrace in #1036 too

**Comment by yatsukhnenko** [comment]
@zhuleilei version 3.1.4RC1 is up on PECL site. Could you reproduce your crash with it?

**Comment by yatsukhnenko** [comment]
Feel free to create new issue if crash will reproduce on 3.1.4
